# Предложения
## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiTmVvIiwiZW1haWwiOiJtckFuZGVyc29uQG1haWwubmV0IiwidXNlclR5cGUiOiJQcm8iLCJpZCI6IjY1NDVlZWQ1N2RmOWUzZDMzOTk3NzRiOCIsImlhdCI6MTY5OTA4MjIxNiwiZXhwIjoxNjk5MjU1MDE2fQ.WvOI06Gyi3AlCw0-rKONnyz15O9O044HXw_W_DH7QGM

###

## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiTmV3IFVTZXIiLCJlbWFpbCI6Im5ld1VzZXJAbWFpbC5uZXQiLCJ1c2VyVHlwZSI6IlVzZXIiLCJpZCI6IjY1NDI0NzU1NGY4OWI0MTk3YzdkOGY1OCIsImlhdCI6MTY5ODg0MjQ1OCwiZXhwIjoxNjk5MDE1MjU4fQ.QkxotG1YGXDAS1RLIRXy0f7JQSNnMTSjzObK1j5RVik
Content-Type: application/json

{
  "title": "B еще одно ТУЦОВОЕ место",
  "description": "Тутцовое местечко для тутцовки",
  "createdDate": "2023-09-23T16:17:26.406Z",
  "city": "Brussels",
  "previewImage": "loft-hell.jpg",
  "images": [
    "loft-hell-1.jpg",
    "loft-hell-2.jpg",
    "loft-hell-3.jpg"
  ],
  "isPremium": true,
  "isFavourites": false,
  "rating": 0,
  "housingType": "apartment",
  "rooms": 5,
  "guestsNumber": 10,
  "price": 99999,
  "comfort": [
    "Air conditioning",
    "Laptop friendly workspace",
    "Fridge"
  ],
  "coordinates": ["48.85661", "2.351499"]
}


###

## Получить объявление по идентификатору
GET http://localhost:5000/offers/654263742fa5719801084195 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiTmV3IFVTZXIiLCJlbWFpbCI6Im5ld1VzZXJAbWFpbC5uZXQiLCJ1c2VyVHlwZSI6IlVzZXIiLCJpZCI6IjY1NDI0NzU1NGY4OWI0MTk3YzdkOGY1OCIsImlhdCI6MTY5ODg0MjQ1OCwiZXhwIjoxNjk5MDE1MjU4fQ.QkxotG1YGXDAS1RLIRXy0f7JQSNnMTSjzObK1j5RVik

###

## Удалить объявление по идентификатору
DELETE http://localhost:5000/offers/6540ad1fd8e6f337ea72d15c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiTGVicm9uZSBGaXJzdCIsImVtYWlsIjoibGViTEFAbWFpbC5uZXQiLCJ1c2VyVHlwZSI6IlBybyIsImlkIjoiNjUzZjczNjAwMDQ1NWY2MWViNzIzY2FmIiwiaWF0IjoxNjk4NzM0MzE1LCJleHAiOjE2OTg5MDcxMTV9.zAo16oVUNMpcvrlCZQJOhRL7Eg2CiZmWnOtyo-egk3M

###

## Обновить объявление

PATCH http://localhost:5000/offers/6540ad1fd8e6f337ea72d15c HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiTGVicm9uZSBGaXJzdCIsImVtYWlsIjoibGViTEFAbWFpbC5uZXQiLCJ1c2VyVHlwZSI6IlBybyIsImlkIjoiNjUzZjczNjAwMDQ1NWY2MWViNzIzY2FmIiwiaWF0IjoxNjk4NzM0MzE1LCJleHAiOjE2OTg5MDcxMTV9.zAo16oVUNMpcvrlCZQJOhRL7Eg2CiZmWnOtyo-egk3M
Content-Type: application/json

{
  "city": "Paris",
  "price": 1200,
  "isPremium": true
}

###

## Получить комментарии к объявлению
GET http://localhost:5000/offers/654263742fa5719801084195/comments HTTP/1.1

###

## Получить премиальные предложения по городу
GET http://localhost:5000/offers/premium/Brussels HTTP/1.1

###

## Получить избранные предложения пользователя
GET http://localhost:5000/offers/bundles/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiTmVvIiwiZW1haWwiOiJtckFuZGVyc29uQG1haWwubmV0IiwidXNlclR5cGUiOiJQcm8iLCJpZCI6IjY1NDVlZWQ1N2RmOWUzZDMzOTk3NzRiOCIsImlhdCI6MTY5OTA4MjIxNiwiZXhwIjoxNjk5MjU1MDE2fQ.WvOI06Gyi3AlCw0-rKONnyz15O9O044HXw_W_DH7QGM

###
